pipeline {
    agent any
        
    stages {
        stage('initialize') {
            steps {
                sh '''
                       export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain com-sample-project --domain-owner 426996824299 --query authorizationToken --output text`
                       export MAVEN_HOME=/usr/lib/apache-maven-3.6.3
                       export PATH=$PATH:$MAVEN_HOME/bin
                       mvn --version
                   '''
            }
        }
        stage('Build'){
            steps{
            sh 'mvn clean install'
            }
            
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        }
    }
}
