pipeline {
    agent {label 'slave'}
  
    stages {
        stage('initialize') {
            steps {
                sh '''
                       ##export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain zuci --domain-owner 678876462442 --query authorizationToken --output text`
                       export MAVEN_HOME=/usr/share/maven
                       export PATH=$PATH:$MAVEN_HOME/bin
                       mvn --version
                   '''
            }
        }
        stage('Build'){
            steps{
                sh '''
                        export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain zuci --domain-owner 678876462442 --query authorizationToken --output text
                        mvn clean install 
                   '''
               
            }
            
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
